### ISSUE TITLE
Sharing from photo apps?

### ISSUE THREAD

**Issue by noctivityinc** [MaxAst/expo-share-extension#17]
Just want to confirm that, at this time, you cant share an image from your photo app or any other app using this library, correct?

**Comment by MaxAst** [comment]
hey @noctivityinc, that's correct. If you need this, contributions are welcome

**Comment by MaxAst** [comment]
Hey @noctivityinc, support for sharing images from the Photos app is now supported! Feel free to check out the README for instructions
