### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by kayode0x** [MaxAst/expo-share-extension#27]
hey Max, I was wondering if there are plans to support android

**Comment by MaxAst** [comment]
At the moment I have no plans to support android. From my experience, the UX for sharing is a little different on android as it does not support custom views, I believe it always redirects to the host app. Will dig into this once I have a need for it.

**Comment by kayode0x** [comment]
i'll request a PR if i make progress.

**Comment by export-mike** [comment]
@MaxAst maybe this module could seemlessly use a intent-filter and launch the ShareExtension.tsx on open for android?

https://github.com/achorein/expo-share-intent
