### ISSUE TITLE
inconsistency in sharing URLs

### ISSUE THREAD

**Issue by kayode0x** [MaxAst/expo-share-extension#28]
TLDR: sharing URLs from safari works, but it doesn't from the website itself (i guess that uses `navigator.share(...)`)

app.config.js
```
[
	"expo-share-extension",
	{
		height: 700,
		activationRules: [
			{ type: "url" },
			{ type: "text" },
			{ type: "image" },
			{ type: "video" },
		],
		backgroundColor: {
			red: 255,
			green: 255,
			blue: 255,
			alpha: 0,
		},
		preprocessingFile: "./ShareExtension/preprocess.js",
		excludedPackages: [
			"expo-font",
			"expo-updates",
			"expo-dev-client",
			"expo-splash-screen",
		],
	},
]
```

https://github.com/MaxAst/expo-share-extension/assets/60462284/52ce623a-6196-4691-acbb-6ef91cad5591

**Comment by kayode0x** [comment]
figured the `preprocessing.js` file and it's activation rule clashes with `activationRules: [{ type: "url" }]`. dropped the file and everything works now.

**Comment by MaxAst** [comment]
glad you resolved it! I actually mention this in the README, but should probably throw an error during prebuild (or filter out the url activation rule if a preprocessing file exists
