### ISSUE TITLE
Issue starting basic example project

### ISSUE THREAD

**Issue by belle-chang** [MaxAst/expo-share-extension#31]
Hi, I'm on step 3 of the `Development` section and running into this problem:

```
[!] An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Consistency issue: no parent for object `ShareExtensionViewController.swift`: `SourcesBuildPhase`, `SourcesBuildPhase`
```

Any ideas and solutions? Not entirely sure how to start the sample app otherwise. Thanks for all your hard work on this plugin!

**Comment by MaxAst** [comment]
Hi @belle-chang, unfortunately I haven't been able to reproduce it. When I cd into examples/basic and run `npm run prebuild`, it runs successfully for me:

![Screenshot 2024-06-06 at 11 28 46](https://github.com/MaxAst/expo-share-extension/assets/13224092/2c463526-e457-44a9-9ec5-5faaa289ff1d)

Can you pls describe the exact steps you take until you reach the error you shared?

**Comment by belle-chang** [comment]
Hi Max!
Thanks for promptly responding. I recloned the project and didn't get that issue again, but got a few others:

1. I got a bunch of issues for importing `expo/config-plugins`, but when I updated the imports to `@expo/config-plugins`, I was able to finish running both `yarn` and the first 2 steps under **Development** (`npm run build` and `npm run build plugin`). Is updating the
 imports to `@expo/config-plugins` the correct solution? Attached an errors text file below.
[errors.txt](https://github.com/user-attachments/files/15637026/errors.txt)
2. After successfully running `npm run prebuild`, I'm running the last command `npm run ios`. Upon opening the basic app on my simulator, I'm seeing this:
![image](https://github.com/MaxAst/expo-share-extension/assets/47519226/85def221-9dce-491e-adc6-d7fa37b61859)

The steps I'm taking are:
1. Running yarn in both the parent expo-share-extension and examples/basic directories
2. Then following the instructions under the **Development** section

**Comment by belle-chang** [comment]
So I was able to fix the second issue by manually installing `babel-plugin-module-resolver` from https://github.com/expo/expo/issues/25923, but still curious about the first question regarding the import of `expo/config-plugins` vs `@expo/config-plugins`

**Comment by belle-chang** [comment]
Hi Max, thanks for the prompt response! using `npm install` fixed both issues and I was able to get the examples up and running. Thank you again!
