### ISSUE TITLE
Debugging help

### ISSUE THREAD

**Issue by belle-chang** [MaxAst/expo-share-extension#36]
Hi Max,

Thanks again for all your great work on this expo plugin! We're in the process of implementing the share sheet for our application, and had some questions about debugging. What's the best way to see the console.log() and print statements for debugging purposes? We're experiencing an issue where our end-to-end flows work properly when testing on the simulator, but not when installed into physical devices (Button is failing to execute onPress fx). I attempted to look at the logs in the Console app, as well as attaching to the process in XCode but couldn't find any of my logs. Also, I noticed you use Alert.alert() in the firebase example, but I wasn't able to get the alert to show up -- do you know why that could be?

Again, thanks so much!!

**Comment by MaxAst** [comment]
also keep in mind that share extension's have a memory cap of 100MB on real devices, so if it's a memory intensive function that gets called on press, the error would not occur on the simulator. You can check how much memory your share extension uses in debug mode, when you start the share extension via XCode

**Comment by MaxAst** [comment]
Hey @belle-chang, any luck? If so, I'd close the issue

**Comment by MaxAst** [comment]
closing this, feel free to comment here if you need more help
