### ISSUE TITLE
Share extension no longer an option after share sheet closed

### ISSUE THREAD

**Issue by nhuesmann** [MaxAst/expo-share-extension#39]
Hi Max,

First of all, thank you so much for this incredible plugin! I can't believe Expo still hasn't directly supported this functionality yet.

I've got an issue as well as a question.

### Issue
- After I show and dismiss the share sheet, if I show it again my share extension no longer appears as an option (until I refresh the page in safari)

![issue](https://github.com/user-attachments/assets/333d9900-4483-4222-9f42-7edcdfd9068d)

### Steps to reproduce
- Launch safari
- Tap share button
- Observe my share extension is an option
- Tap above the share sheet to dismiss the share sheet
- Tap share button
- Observe my share extension is no longer an option
- Refresh the page
- Tap share button
- Observe my share extension is an option

I'm using Expo SDK 50.

### Additional Question
Sorry, wasn't sure the best place to put this so I figured I'd ask here. I noticed in a separate open issue you mentioned being able to view the current memory usage of the share extension - could you point me to any documentation or details on how to do that? I'm running into memory issues when I run the share extension on my native device (What I showed in the demo is a stripped down version for demo purposes).

Thank you!

**Comment by nhuesmann** [comment]
Regarding my additional question, I figured out how to debug the share extension to see memory usage. I stripped the extension down to just rendering a single view and text and it was still using 70mb. Is that because I'm not running in release mode? I tried running my app with `--no-dev --minify` but ran into an issue when launching the share extension: `Error: React Refresh runtime should not be included in the production bundle`. It just crashes before it can load when trying it this way. Any tips? I cant imagine that a view and some text should be using up almost all the allotted memory.

**Comment by MaxAst** [comment]
Hi @nhuesmann, if the share extension no longer appears it is indeed most likely a memory issue. React native uses 60-70mb by default in dev mode, so this is expected. In release mode, it's about 30-40mb. However, since the limit is 120mb for share extensions, this shouldn't be an issue. Are you using the basic example in your demo video, or are you doing anything else that might be consuming memory?

**Comment by MaxAst** [comment]
and does this only happen in debug mode or also in release mode?

**Comment by nhuesmann** [comment]
Not encountering this issue anymore, closing for now
