### ISSUE TITLE
No text data when sharing from certain apps to expo share extension

### ISSUE THREAD

**Issue by nhuesmann** [MaxAst/expo-share-extension#56]
This issue has to do with using another iOS app's share functionality to share to my react native app running expo share extension. The specific app in question is Home Depot. How to reproduce:

1. Install the Home Depot app
2. Nav to a product screen in the home depot app and tap the share button in the upper right of the toolbar
3. Choose the react native app running expo share extension
4. Observe that `InitialProps` has a `text` property present, but it is an empty string
5. Dismiss share extension and try sharing again from within the home depot app, but this time choose any other source (copy, messages, mail). Notice there is text content there.

I've tried enabling all `activationRules` in `app.json`, carefully following all steps in the docs, and the issue persists. I haven't tried a preprocessing js file because the presence of said file was breaking functionality previously. Also note that sharing from Safari/other browsers as well as just plain text are all working fine.

My phone is running the latest iOS at time of writing (18.1).

Not sure why the share extension is failing to capture this text, but it'd be great to get this working. Thanks!

**Comment by MaxAst** [comment]
Hi Nate, will have a look, thanks for reporting! And also thanks a lot for the generous sponsorship @nhuesmann! ❤️😊

**Comment by MaxAst** [comment]
Hi @nhuesmann, apologies for getting back to this so late. I just created [a PR with a new kitchen sink example](https://github.com/MaxAst/expo-share-extension/pull/62). I ran it with a development build on my device and tried it on Amazon and Mr Porter, where I was able to retrieve both, text and URL, when using their share functionality. Unfortunately I can't download Home Depot in Germany, but I would expect their sharing functionality works similar. Have you tried it with the latest version (2.0.1)?

|Amazon|Mr Porter|
|--------|-------|
| ![IMG_8691](https://github.com/user-attachments/assets/d271dd0a-964c-46c4-bc07-1a74c4fc6c6a) | ![IMG_8692](https://github.com/user-attachments/assets/b437986a-7f05-47fc-a9a6-96a6d2d0aaab) |

**Comment by MaxAst** [comment]
Closing this for now as I'm pretty sure it's just a matter of choosing the right values in `activationRules`. Lmk if you still run into issues @nhuesmann
